### ISSUE TITLE
pgcenter crashes when no running postgres 

### ISSUE THREAD

**Issue by lesovsky** [lesovsky/pgcenter#66]
no running postgres
```
$ ps aux|grep postgres
lesovsky  8716  0.0  0.0  15652  1080 pts/5    S+   19:30   0:00 grep --colour=auto postgres
```

trying to run pgcenter and oops.
```
$ pgcenter top
panic: interface conversion: error is *net.OpError, not *pq.Error

goroutine 1 [running]:
github.com/lesovsky/pgcenter/lib/utils.PQconnectdb(0xb02f60, 0xc00001a240, 0x25, 0x6b19d0, 0x7919a0, 0x0)
        /home/lesovsky/Git/pgcenter/lib/utils/postgres.go:87 +0x4fc
github.com/lesovsky/pgcenter/lib/utils.CreateConn(0xb02f60, 0x0, 0x0, 0xb02f60)
        /home/lesovsky/Git/pgcenter/lib/utils/postgres.go:44 +0x3d
github.com/lesovsky/pgcenter/top.RunMain(0xb1ff08, 0x0, 0x0, 0x0, 0x0, 0x1538, 0x0, 0x0, 0x0, 0x0, ...)
        /home/lesovsky/Git/pgcenter/top/top.go:29 +0xbf
github.com/lesovsky/pgcenter/cmd/top.glob..func1(0xafea60, 0xb1ff08, 0x0, 0x0)
        /home/lesovsky/Git/pgcenter/cmd/top/top.go:23 +0x72
github.com/spf13/cobra.(*Command).execute(0xafea60, 0xb1ff08, 0x0, 0x0, 0xafea60, 0xb1ff08)
        /home/lesovsky/Git/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xafde80, 0x73f498, 0xc000057f88, 0xc00001c1d8)
        /home/lesovsky/Git/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
        /home/lesovsky/Git/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /home/lesovsky/Git/pgcenter/pgcenter.go:8 +0x2e
```

**Comment by lesovsky** [comment]
fixed 73c4701
