### ISSUE TITLE
runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by patsevanton** [lesovsky/pgcenter#73]
Sometime if choice "pg_stat_statements input/output" pgcenter fail with kernel panic.
PostgreSQL 11.6

```
SELpanic: runtime error: slice bounds out of range [:-1], seqmax, seqmin,
postgres  xxxxx~  54        132       0         0         c8c520c~  SELECT tableoid, oid, conname, pg_catalog.pg_get_constraintdef(oid) AS co
goroutine 1 [running]:6       6         0         0         84d9044~  SELECT tableoid, oid, conname, confrelid, pg_catalog.pg_get_constraintdef
github.com/lesovsky/pgcenter/top.printStatData(0xc0001dc2d0, 0xc000a6a7d0, 0xc0057b8900)id, conname, confrelid, pg_catalog.pg_get_constraintdef
postgres/home/travis/gopath/src/github.com/lesovsky/pgcenter/top/stat.go:246 +0x632um, a.attname, a.atttypmod, a.attstattarget, a.attstorage, t
github.com/lesovsky/pgcenter/top.printDbstat(0xc0001dc2d0, 0x40319c28f5c28f5c, 0x402e1eb851eb851f, 0x402a8f5c28f5c28f, 0xc004123be8, 0x3, 0x41d49133e9c00000, 0x4080c80000000000, 0x4193dd25cc000000, 0x4195ce0878000000, ...)ableoid, oid, adnum, pg_catalog.pg_get_expr(adbin, adrelid) AS ad
postgres/home/travis/gopath/src/github.com/lesovsky/pgcenter/top/stat.go:181 +0xc4tableoid, pol.polname, pol.polcmd, pol.polpermissive, CASE WH
github.com/lesovsky/pgcenter/top.printAllStat.func1(0xc00014c000, 0xc000a6b904, 0x3) tgfoid::pg_catalog.regproc AS tgfname, pg_catalog.pg_get_t
postgres/home/travis/gopath/src/github.com/lesovsky/pgcenter/top/stat.go:92 +0x489_in_recovery()                                               
github.com/jroimartin/gocui.(*Gui).consumeevents(0xc00014c000, 0x0, 0x0)LECT pg_get_userbyid(p.userid) AS user, d.datname AS database, date_tru
postgres/home/travis/gopath/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:399 +0x1e8byid(p.userid) AS user, d.datname AS database, p.shared
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc00014c000, 0x845e38, 0xc00014c000)me, tgfoid::pg_catalog.regproc AS tgfname, pg_catalog.pg_get_t
postgres/home/travis/gopath/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:381 +0x206$1, now() - pg_postmaster_start_time())                
github.com/lesovsky/pgcenter/top.uiLoop(0xb18f00, 0x0)      e2a899f~  SET deadlock_timeout TO 1000                                             
postgres/home/travis/gopath/src/github.com/lesovsky/pgcenter/top/ui.go:49 +0x156cription from pg_catalog.pg_description where objoid = $1 and c
github.com/lesovsky/pgcenter/top.RunMain(0xc00008c540, 0x0, 0x2, 0x7ffdd641473f, 0x13, 0x1538, 0x0, 0x0, 0x0, 0x0, ...),2) AS avg_query, sum(ca
postgres/home/travis/gopath/src/github.com/lesovsky/pgcenter/top/top.go:43 +0x194                                                              
github.com/lesovsky/pgcenter/cmd/top.glob..func1(0xb14540, 0xc00008c540, 0x0, 0x2)tableoid, pol.polname, pol.polcmd, pol.polpermissive, CASE WH
postgres/home/travis/gopath/src/github.com/lesovsky/pgcenter/cmd/top/top.go:23 +0x72eoid, pr.oid, p.pubname FROM pg_publication_rel pr, pg_publ
github.com/spf13/cobra.(*Command).execute(0xb14540, 0xc00008c520, 0x2, 0x2, 0xb14540, 0xc00008c520)                                            
postgres/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aag_stat_statements(IN showtext boolean, OUT userid oid, O
github.com/spf13/cobra.(*Command).ExecuteC(0xb13960, 0x0, 0x78e840, 0xc000074058)ize_pretty(pg_database_size($1))                              
postgres/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2eaers CASCADE                                             
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/home/travis/gopath/src/github.com/lesovsky/pgcenter/pgcenter.go:8 +0x2d
```

**Comment by patsevanton** [comment]
![image](https://user-images.githubusercontent.com/10828883/77619637-da68c980-6f62-11ea-91f7-d1db6f72228a.png)

**Comment by patsevanton** [comment]
Postgresql 10.6

![image](https://user-images.githubusercontent.com/10828883/77619726-0ab06800-6f63-11ea-918a-ffc7d93183c6.png)

**Comment by patsevanton** [comment]
PostgreSQL 9.6
![image](https://user-images.githubusercontent.com/10828883/77619851-477c5f00-6f63-11ea-87cf-2aa36283caa1.png)

**Comment by patsevanton** [comment]
This panic on server with issue https://github.com/lesovsky/pgcenter/issues/72

**Comment by patsevanton** [comment]
Same error on PostgreSQL 11.6 Single Node
![image](https://user-images.githubusercontent.com/10828883/77621764-464d3100-6f67-11ea-84ca-3432122ed477.png)

**Comment by lesovsky** [comment]
What is the version of pg_stat_statements used there? The version can be found in the `\dx` output.

**Comment by lesovsky** [comment]
If the bug still can be reproduced could you dump content of pg_stat_statements (text of queries could be truncated up to first word) and send it to me.

**Comment by patsevanton** [comment]
```pg_stat_statements | 1.6```

**Comment by lesovsky** [comment]
commited potential fix into dev branch 7fd386c, try to reproduce the bug.

**Comment by patsevanton** [comment]
![Снимок экрана от 2020-04-29 18-18-50](https://user-images.githubusercontent.com/10828883/80595309-56649e80-8a46-11ea-85fd-65f0a486d8d4.jpg)


Issue is reproduce.

**Comment by NikolayS** [comment]
@lesovsky also got it yesterday, while preparing my tutorial for PGCon:

![Screen Shot 2020-05-25 at 16 09 14](https://user-images.githubusercontent.com/1345402/82847283-1f957300-9ea2-11ea-8bba-ba9ceaea1369.png)

**Comment by lesovsky** [comment]
Panic occurs due to data race condition, but proper fix requires a lot of refactoring and internal redesign. Currently I do this but I cannot say how much time it will take.

**Comment by lesovsky** [comment]
@NikolayS, @patsevanton try to reproduce on v0.7.0.

**Comment by patsevanton** [comment]
I try pgbench on PostgreSQL13 - ok.
