### ISSUE TITLE
Environment variable PGHOSTADDR not supported

### ISSUE THREAD

**Issue by take-five** [lesovsky/pgcenter#86]
Hi

We're using a bastion host and SSH-tunnels to connect to Postgres in Amazon RDS from outside of VPC networks. To support `sslmode=verify-full` we use environment variable `PGHOSTADDR` that contains DNS-name of RDS-host, but we actually connect to SSH-tunnel on localhost.

It works fine with **psql** and other **libpq**-based programs, but `pgcenter` panics and crashes with error:
```
panic: setting PGHOSTADDR not supported
```

**Comment by lesovsky** [comment]
Hi, thanks for report
which version of pgcenter?

**Comment by take-five** [comment]
I installed it today using `go get github.com/lesovsky/pgcenter`

**Comment by lesovsky** [comment]
Unfortunately it is not a bug of pgcenter, it is related to how postgres drivers implement libpq environment variables.
Before 0.7.0 lib/pq driver is used and starting from 0.7.0 jackc/pgx is used. But neither [lib/pg](https://github.com/lib/pq/blob/master/conn.go#L1966), nor [jackc/pgx](https://github.com/jackc/pgconn/blob/master/config.go#L356) don't support PGHOSTADDR and even more vars.

At the same time I concerned about `panic`. Are you sure is this a panic with stack traces (which looks like panics [here](https://github.com/lesovsky/pgcenter/issues/73)), or just error message?

**Comment by take-five** [comment]
Okay, so, basically, the problem is within 3rd party libraries. That makes sense.

Yes, it was *panic*, I simply omitted stacktrace in the original message. Do you want me to provide full error message with the stacktrace?

**Comment by lesovsky** [comment]
In case of panic it make sense only if pgcenter v0.7.0 used (check the output of `pgcenter --version`)

**Comment by take-five** [comment]
`pgcenter --version` doesn't display anything for me since I obtained with `go get` (the only for way for me try since I'm on Mac OS):
```
$ pgcenter --version
pgcenter  -
```

Here's the full error message:
```
panic: setting PGHOSTADDR not supported

goroutine 1 [running]:
github.com/lib/pq.parseEnviron.func2(...)
	/Users/amikhailov/work/src/github.com/lib/pq/conn.go:1957
github.com/lib/pq.parseEnviron(0xc000081400, 0x3c, 0x3c, 0xc0000a3950)
	/Users/amikhailov/work/src/github.com/lib/pq/conn.go:1970 +0x1236
github.com/lib/pq.NewConnector(0xc000100270, 0x25, 0xc0000df698, 0xc000092a20, 0xc000092a20)
	/Users/amikhailov/work/src/github.com/lib/pq/connector.go:56 +0x13e
github.com/lib/pq.DialOpen(0x14cab00, 0xc000092a20, 0xc000100270, 0x25, 0xc000094190, 0x4, 0xc0000c3d60, 0x174f960)
	/Users/amikhailov/work/src/github.com/lib/pq/conn.go:286 +0x39
github.com/lib/pq.Open(...)
	/Users/amikhailov/work/src/github.com/lib/pq/conn.go:281
github.com/lib/pq.Driver.Open(0xc000100270, 0x25, 0x1b, 0xc0000a3590, 0xe, 0xc0000df998)
	/Users/amikhailov/work/src/github.com/lib/pq/conn.go:54 +0x9a
database/sql.dsnConnector.Connect(...)
	/usr/local/Cellar/go/1.14.4/libexec/src/database/sql/sql.go:688
database/sql.(*DB).conn(0xc000130000, 0x14ce9c0, 0xc0000b8008, 0xc0000dfa01, 0x100e246, 0xc000130000, 0xc0)
	/usr/local/Cellar/go/1.14.4/libexec/src/database/sql/sql.go:1228 +0x201
database/sql.(*DB).query(0xc000130000, 0x14ce9c0, 0xc0000b8008, 0x1429ad9, 0x8, 0x0, 0x0, 0x0, 0xc0000a0e01, 0x10, ...)
	/usr/local/Cellar/go/1.14.4/libexec/src/database/sql/sql.go:1565 +0x66
database/sql.(*DB).QueryContext(0xc000130000, 0x14ce9c0, 0xc0000b8008, 0x1429ad9, 0x8, 0x0, 0x0, 0x0, 0xc0000dfad8, 0x100eab8, ...)
	/usr/local/Cellar/go/1.14.4/libexec/src/database/sql/sql.go:1547 +0xd1
database/sql.(*DB).QueryRowContext(...)
	/usr/local/Cellar/go/1.14.4/libexec/src/database/sql/sql.go:1648
database/sql.(*DB).QueryRow(0xc000130000, 0x1429ad9, 0x8, 0x0, 0x0, 0x0, 0xc000100270)
	/usr/local/Cellar/go/1.14.4/libexec/src/database/sql/sql.go:1659 +0x8b
github.com/lesovsky/pgcenter/lib/utils.PQstatus(0xc000130000, 0x8, 0xc000100270)
	/Users/amikhailov/work/src/github.com/lesovsky/pgcenter/lib/utils/postgres.go:204 +0x6f
github.com/lesovsky/pgcenter/lib/utils.PQconnectdb(0x174e760, 0xc000100270, 0x25, 0x5, 0xc0000929b0, 0xc0000a3890)
	/Users/amikhailov/work/src/github.com/lesovsky/pgcenter/lib/utils/postgres.go:82 +0x88
github.com/lesovsky/pgcenter/lib/utils.CreateConn(0x174e760, 0x0, 0x0, 0x174e760)
	/Users/amikhailov/work/src/github.com/lesovsky/pgcenter/lib/utils/postgres.go:44 +0x3d
github.com/lesovsky/pgcenter/top.RunMain(0x1779870, 0x0, 0x0, 0x0, 0x0, 0x1538, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/amikhailov/work/src/github.com/lesovsky/pgcenter/top/top.go:29 +0xd2
github.com/lesovsky/pgcenter/cmd/top.glob..func1(0x174a3c0, 0x1779870, 0x0, 0x0)
	/Users/amikhailov/work/src/github.com/lesovsky/pgcenter/cmd/top/top.go:23 +0x72
github.com/spf13/cobra.(*Command).execute(0x174a3c0, 0x1779870, 0x0, 0x0, 0x174a3c0, 0x1779870)
	/Users/amikhailov/work/src/github.com/spf13/cobra/command.go:854 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x17496a0, 0x0, 0x0, 0xc000096058)
	/Users/amikhailov/work/src/github.com/spf13/cobra/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/amikhailov/work/src/github.com/spf13/cobra/command.go:895
main.main()
	/Users/amikhailov/work/src/github.com/lesovsky/pgcenter/pgcenter.go:8 +0x2d
```

**Comment by lesovsky** [comment]
Ага, looks like an old version is used, due to `github.com/lib/pq` in stack trace (and go 1.14.4 confuses a bit). I would strongly recommended to use packages from [releases](https://github.com/lesovsky/pgcenter/releases) page. I spent a lot of time to setup releases )))

**Comment by take-five** [comment]
The *panic* disappeared after I upgraded Go and rebuilt *pgcenter* from scratch.
I think the issue can be closed :)
Thank you.
