### ISSUE TITLE
Not work in centos 8.3 docker postgrespro-standard

### ISSUE THREAD

**Issue by strav66** [lesovsky/pgcenter#87]
Docker postgrespro-standard work in centos 8.3

pgcenter 0.6.6 work in docker
docker exec -it srv-db-APSD-VO pgcenter --version
pgcenter v0.6.6 4f87424-master

![изображение](https://user-images.githubusercontent.com/80037871/109950548-af980100-7ced-11eb-8182-286042d77e4c.png)

pgcenter 0.70 not work docker:
docker exec -it srv-db-APSD-VO /opt/pgpro/data/pgcenter --version
pgcenter v0.7.0 45c8bf0d0098f377692be886691eba9ee6005808-release

docker exec -it srv-db-APSD-VO /opt/pgpro/data/pgcenter top -h localhost

panic: send on closed channel

goroutine 65 [running]:
github.com/lesovsky/pgcenter/top.collectStat(0x9e5620, 0xc000138c40, 0xc000122080, 0xc000382000, 0xc0001281e0)
        /home/runner/work/pgcenter/pgcenter/top/stat.go:57 +0x371
github.com/lesovsky/pgcenter/top.doWork.func1(0x9e5620, 0xc000138c40, 0xc000148000, 0xc000382000, 0xc000380000)
        /home/runner/work/pgcenter/pgcenter/top/ui.go:77 +0x65
created by github.com/lesovsky/pgcenter/top.doWork
        /home/runner/work/pgcenter/pgcenter/top/ui.go:76 +0xeb

**Comment by lesovsky** [comment]
Hi, thanks for report,
What docker image is used?

**Comment by strav66** [comment]
my build docker

[Dockerfile.zip](https://github.com/lesovsky/pgcenter/files/6082945/Dockerfile.zip)

**Comment by lesovsky** [comment]
What happen if run container and then run pgcenter being inside?
Like:
```
docker run --rm -ti IMAGE /bin/bash
pgcenter top ...
```

**Comment by strav66** [comment]
Работает, но странно:
/opt/pgpro/data/pgcenter top -h localhost

![изображение](https://user-images.githubusercontent.com/80037871/109962920-dad61c80-7cfc-11eb-8c45-5dd8cb2af679.png)

нет статистики: процессор, память и т.д.

Если запускать так (внутри docker):
/opt/pgpro/data/pgcenter top

тогда ругается:
failed to connect to `host=/var/run/postgresql user=postgres database=`: dial error (dial unix /var/run/postgresql/.s.PGSQL.5432: connect: no such file or directory)

для 0.6.6 соответственно:
pgcenter top -h localhost

![изображение](https://user-images.githubusercontent.com/80037871/109963289-4a4c0c00-7cfd-11eb-87cf-0668fe51f093.png)

pgcenter top
![изображение](https://user-images.githubusercontent.com/80037871/109963465-7f585e80-7cfd-11eb-9c4d-78b8511e71e9.png)

Всё отлично и со статистикой

**Comment by lesovsky** [comment]
I tested various cases using different docker images and bug reproduced in most of cases. Sometimes pgcenter starts as expected but at next, the same attempt it crashed again. I suspect there something related to UI processing when docker starts, but need to dig deeper.
I changed the title of the issue to reflect the problem more precisely.

*Also I strongly recommended to avoid using national languages and post comments using English*.

**Comment by strav66** [comment]
OK

tried 10 times sequentially run pgcenter 0.7.0:
  docker exec -it srv-db-APSD-VO /opt/pgpro/data/pgcenter top -h localhost
6 times started with errors, 3 times - ok (but without CPU statistics, etc.)

error:
panic: send on closed channel

goroutine 53 [running]:
github.com/lesovsky/pgcenter/top.collectStat(0x9e5620, 0xc000310040, 0xc000122080, 0xc000326000, 0xc0001281e0)
        /home/runner/work/pgcenter/pgcenter/top/stat.go:57 +0x371
github.com/lesovsky/pgcenter/top.doWork.func1(0x9e5620, 0xc000310040, 0xc000140000, 0xc000326000, 0xc000318010)
        /home/runner/work/pgcenter/pgcenter/top/ui.go:77 +0x65
created by github.com/lesovsky/pgcenter/top.doWork
        /home/runner/work/pgcenter/pgcenter/top/ui.go:76 +0xeb

pgcentert 0.6.6 - never broke (maybe I was just lucky)

**Comment by lesovsky** [comment]
Hi,
check out new [v0.8.0](https://github.com/lesovsky/pgcenter/releases/tag/v0.8.0) release, both issues related to absence of stats and panic are fixed. Waiting for testing and feedback.

**Comment by strav66** [comment]
pgcenter 0.8.0 works  fine!

![изображение](https://user-images.githubusercontent.com/80037871/110428821-feadaf80-80ba-11eb-8889-3ab6d1b2e11c.png)

**Comment by strav66** [comment]
Addition:
when exiting (closing pgcenter) an error occurs:

panic: runtime error: slice bounds out of range [:-1]

goroutine 49 [running]:
github.com/nsf/termbox-go.Init.func1()
        /home/runner/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20180819125858-b66b20ab708e/api.go:95 +0x36a
created by github.com/nsf/termbox-go.Init
        /home/runner/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20180819125858-b66b20ab708e/api.go:84 +0x730

**Comment by strav66** [comment]
> What about attempt to reproduce using `lesovsky/pgcenter:v0.8.0` image?

tried lesovsky / pgcenter: v0.8.0 image
The error was not reproduced

but it is not possible to use the name localhost with it!
I think the error is related to localhost

> 
> > my docker image

https://github.com/lesovsky/pgcenter/issues/87#issuecomment-790519621

> It is insufficient information, provide more details... base image, full command definition of how pgcenter was started (including docker opts).

docker runs via docker-compose ([docker-compose.yml.tar.gz](https://github.com/lesovsky/pgcenter/files/6108013/docker-compose.yml.tar.gz)):
`docker-compose up -d`

pgcenter upload volume PGDATA 
run pgcenter and connect to a running docker with the command:

`docker exec -it srv-db1C-ERP /opt/pgpro/data/pgcenter top -h localhost`

after a few minutes (3-4), sometimes an error occurs (pgcenter continues to work!):

 kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
 
If it is ok to exit pgcenter (with the q key) the message appears:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 49 [running]:
github.com/nsf/termbox-go.Init.func1()
        /home/runner/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20180819125858-b66b20ab708e/api.go:95 +0x36a
created by github.com/nsf/termbox-go.Init
        /home/runner/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20180819125858-b66b20ab708e/api.go:84 +0x730


```

**Comment by lesovsky** [comment]
Trying to build the image, need the values of variables from docker-compose:
```
    build:
      context: ../docker/postgrespro-standard

      dockerfile: Dockerfile.${PG_Version}
      args: 
        - SERVER_VERSION=${PG_Version}
        - SERVER_VERSION_DOT=${PG_Version_dot}
        - KEYS_DOT=${rpm_keys_dot}
```
No need `SERVER_VERSION`, but need other values of `SERVER_VERSION_DOT`, `KEYS_DOT` and maybe content of `../docker/postgrespro-standard` (but not sure).

**Comment by strav66** [comment]
docker-compose.yml.tar.gz

**Comment by lesovsky** [comment]
Oh, hidden file ))) yep, found now

**Comment by strav66** [comment]
and if you build an image with the following command, then you may not even notice it:
`docker-compose build`

**Comment by lesovsky** [comment]
Both ways failed due to necessary files are not exists.

1. using `docker-compose build`
```
docker-compose build
ERROR: build path /tmp/docker/postgrespro-standard either does not exist, is not accessible, or is not a valid URL
```

2. manual docker build also fails
```
docker build --build-arg SERVER_VERSION=12 --build-arg SERVER_VERSION_DOT=6.1 --build-arg KEYS_DOT=0.3 -t local/pg1c:dev -f Dockerfile.10 .
... too many lines ...
COPY failed: file not found in build context or excluded by .dockerignore: stat container/docker-entrypoint.sh: file does not exist
```

Also such files are not found in attached archives. Maybe you just build and publish the image on DockerHub?

**Comment by strav66** [comment]
Complete set of everything you need for build image
[docker-compose-build.tar.gz](https://github.com/lesovsky/pgcenter/files/6108524/docker-compose-build.tar.gz)

Unpack it into some folder
go to the ERP folder
we give the command:

`docker-compose build`

Profit

**Comment by lesovsky** [comment]
Thanks, build successful.

**Comment by lesovsky** [comment]
Spent a quite lot of time for testing and could not reproduce the panic at quit. Also I have no idea how to catch this using unit-tests.

Would like to clarify, are you sure you build the image with proper version of pgcenter (v0.8.0)? Because I manually changed pgcenter's version in your files before build. Maybe you catch error with old version (the similarly as it was [here](https://github.com/lesovsky/pgcenter/issues/88#issuecomment-795835420))?

**Comment by lesovsky** [comment]
Closing this issue — both problems reported here are resolved.

**1. `panic: send on closed channel`** (the original report)
Fixed in v0.8.0. Confirmed working by the reporter.

**2. `panic: runtime error: slice bounds out of range [:-1]` at exit** (follow-up)
This panic was inside `github.com/nsf/termbox-go@v0.0.0-20180819`, triggered by Docker network interface instability (`kernel:unregister_netdevice: waiting for lo to become free`) in the custom image. It was **not** reproducible with the official `lesovsky/pgcenter:v0.8.0` image.

The current codebase (v0.10.0) uses `termbox-go v1.1.1` — a proper tagged release that includes fixes for the resize/cleanup race present in the old pre-release snapshot. The affected code path at `api.go:95` has been rewritten in newer versions.

If you still observe any panic on exit with v0.10.0, please open a new issue with full environment details and pgcenter version.
