### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by makeconfig2017** [lesovsky/pgcenter#99]
**Describe the bug**
While switching pg_stat_statements switch with 'x' getting panic:
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/lesovsky/pgcenter/top.printStatData(0xc0001bc2d0, 0x4000666666666666, 0x40087ae147ae147b, 0x40095c28f5c28f5c, 0x3c6d, 0x3bd, 0x1839, 0x1e83, 0x1dfd, 0x86, ...)
        /home/runner/work/pgcenter/pgcenter/top/stat.go:394 +0x677
github.com/lesovsky/pgcenter/top.printDbstat(0xc0001bc2d0, 0xc0001241c0, 0x4000666666666666, 0x40087ae147ae147b, 0x40095c28f5c28f5c, 0x3c6d, 0x3bd, 0x1839, 0x1e83, 0x1dfd, ...)
        /home/runner/work/pgcenter/pgcenter/top/stat.go:309 +0x14f
github.com/lesovsky/pgcenter/top.printStat.func1(0xc0001b2000, 0xc0001d79e0, 0x0)
        /home/runner/work/pgcenter/pgcenter/top/stat.go:135 +0x73b
github.com/jroimartin/gocui.(*Gui).consumeevents(0xc0001b2000, 0xc0001d7b10, 0x0)
        /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:399 +0x1b4
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc0001b2000, 0x946418, 0x9b5380)
        /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:381 +0x1fa
github.com/lesovsky/pgcenter/top.mainLoop(0x9b53b8, 0xc0000b8010, 0xc000100780, 0x0, 0xc0000b8530)
        /home/runner/work/pgcenter/pgcenter/top/ui.go:45 +0x225
github.com/lesovsky/pgcenter/top.RunMain(0xc000120000, 0x0, 0x0)
        /home/runner/work/pgcenter/pgcenter/top/top.go:30 +0x19b
github.com/lesovsky/pgcenter/cmd/top.glob..func1(0xc19f20, 0xc0000c67e0, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/pgcenter/pgcenter/cmd/top/top.go:31 +0xc5
github.com/spf13/cobra.(*Command).execute(0xc19f20, 0xc0000c67c0, 0x2, 0x2, 0xc19f20, 0xc0000c67c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc1a180, 0xc00004e778, 0xc000093f78, 0x406365)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /home/runner/work/pgcenter/pgcenter/cmd/pgcenter.go:62 +0x31

**Environment**
Describe the environment where the bug occurred.
- OS: [NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Twenty Nine)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"]
- pgCenter Version [pgcenter v0.8.0 df1cea5201ee10e6a9b99fae6a45bc5a3a4f70b4-release]
- pgCenter installation method: [https://github.com/lesovsky/pgcenter/releases/tag/v0.8.0]
- PostgreSQL Version [PostgreSQL 10.17 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2), 64-bit]

**To Reproduce**
Run pgcenter top
Switch pg_stat_statements with 'x' 

**Expected behavior**
Switching pg_stat_statements

**Comment by lesovsky** [comment]
Hmm, is this occur every time you press 'x' or randomly?

**Comment by lesovsky** [comment]
Could you try to reproduce the issue using the master branch? This should be fixed 9adb560.

**Comment by lesovsky** [comment]
**Root cause found and fixed** in PR #136.

The panic `slice bounds out of range [:-1]` (and the subsequent "zero or negative width" error after `9adb560`) had the following trigger sequence:

1. User presses `x` — `viewSwitchHandler` immediately sets `config.view` to the new view (`Aligned = false`, empty `ColsWidth`)
2. The stats collector goroutine is mid-query for the **old** view
3. The old-view result arrives at `printDbstat` first: `Aligned = false` → `SetAlign` fires and populates `ColsWidth` for **N columns** (old view), sets `Aligned = true`
4. The next result has **M > N columns** from the new view — `Aligned = true` skips `SetAlign`
5. `printStatData` iterates `s.Result.Cols` (M entries), `config.view.ColsWidth[N..M-1]` returns `0` (missing map keys)
6. `String[:0-1]` → panic

**Fix**: `alignViewToResult()` now re-runs `SetAlign` whenever `len(ColsWidth) != r.Ncols`, regardless of the `Aligned` flag. This ensures correct alignment even when the first stat batch after a view switch carries the old view's column count.

Test `Test_alignViewToResult` covers this exact scenario (5-column `ColsWidth` + 13-column result → panic path).
